version: 2
updates:
  # NuGet packages for .NET
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "dotnet"
    # Group minor and patch updates
    groups:
      nuget-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Only security updates for major versions
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions - less frequent
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "github-actions"

  # Docker dependencies - quarterly
  - package-ecosystem: "docker"
    directory: "/src/Server"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "docker"