version: '3.8'

# GameLAN VPN Server - Simple Docker Deployment
# Just run: docker-compose up -d

services:
  gamelanvpn:
    container_name: gamelanvpn
    image: gamelanvpn:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"    # Web interface & API
    volumes:
      - ./data:/app/data       # Database storage
      - ./logs:/app/logs       # Log files
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/gamelanvpn.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
  logs: