name: Auto-merge Dependabot

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
    - name: Check if PR is from Dependabot
      id: dependabot-check
      run: |
        if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
          echo "is_dependabot=true" >> $GITHUB_OUTPUT
        else
          echo "is_dependabot=false" >> $GITHUB_OUTPUT
        fi

    - name: Get PR details
      id: pr-details
      run: |
        echo "PR Title: ${{ github.event.pull_request.title }}"
        echo "PR Body: ${{ github.event.pull_request.body }}"

        # Check if it's a minor or patch update
        if [[ "${{ github.event.pull_request.title }}" =~ (patch|minor) ]]; then
          echo "is_safe_update=true" >> $GITHUB_OUTPUT
        else
          echo "is_safe_update=false" >> $GITHUB_OUTPUT
        fi

    - name: Auto-approve safe updates
      if: steps.dependabot-check.outputs.is_dependabot == 'true' && steps.pr-details.outputs.is_safe_update == 'true'
      run: |
        gh pr review ${{ github.event.pull_request.number }} --approve \
          --body "Auto-approved by workflow for safe dependency update"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto-merge safe updates
      if: steps.dependabot-check.outputs.is_dependabot == 'true' && steps.pr-details.outputs.is_safe_update == 'true'
      run: |
        # Wait for checks to pass
        sleep 30

        gh pr merge ${{ github.event.pull_request.number }} \
          --auto --squash \
          --subject "🔄 Auto-merge: ${{ github.event.pull_request.title }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment on manual review needed
      if: steps.dependabot-check.outputs.is_dependabot == 'true' && steps.pr-details.outputs.is_safe_update == 'false'
      run: |
        gh pr comment ${{ github.event.pull_request.number }} \
          --body "⚠️ **Major version update detected!**

          This PR requires manual review before merging.

          Please check:
          - Breaking changes in changelog
          - Compatibility with current codebase
          - Test results

          If everything looks good, you can approve and merge manually."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}