name: Auto-merge Dependabot

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Check if PR is from Dependabot
      id: dependabot-check
      run: |
        if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
          echo "is_dependabot=true" >> $GITHUB_OUTPUT
        else
          echo "is_dependabot=false" >> $GITHUB_OUTPUT
        fi

    - name: Get PR details
      id: pr-details
      run: |
        echo "PR Title: ${{ github.event.pull_request.title }}"
        echo "PR Body: ${{ github.event.pull_request.body }}"

        # Check if it's a minor or patch update
        if [[ "${{ github.event.pull_request.title }}" =~ (patch|minor) ]]; then
          echo "is_safe_update=true" >> $GITHUB_OUTPUT
        else
          echo "is_safe_update=false" >> $GITHUB_OUTPUT
        fi

    - name: Auto-approve safe updates
      if: steps.dependabot-check.outputs.is_dependabot == 'true' && steps.pr-details.outputs.is_safe_update == 'true'
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
          -d '{"event":"APPROVE","body":"Auto-approved by workflow for safe dependency update"}'
      continue-on-error: true

    - name: Enable auto-merge for safe updates
      if: steps.dependabot-check.outputs.is_dependabot == 'true' && steps.pr-details.outputs.is_safe_update == 'true'
      run: |
        # Wait for checks to pass
        sleep 30

        curl -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
          -d '{"commit_title":"🔄 Auto-merge: ${{ github.event.pull_request.title }}","merge_method":"squash"}'
      continue-on-error: true

    - name: Comment on manual review needed
      if: steps.dependabot-check.outputs.is_dependabot == 'true' && steps.pr-details.outputs.is_safe_update == 'false'
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          -d '{"body":"⚠️ **Major version update detected!**\n\nThis PR requires manual review before merging.\n\nPlease check:\n- Breaking changes in changelog\n- Compatibility with current codebase\n- Test results\n\nIf everything looks good, you can approve and merge manually."}'
      continue-on-error: true